### ISSUE TITLE
Please rename test/widget-mvc.el

### ISSUE THREAD

**Issue by tarsius** [kiwanami/emacs-widget-mvc#17]
Beside the library `./widget-mvc.el`, there is a second file by that name at `./test/widget.el` (edit: I meant `/test/widget-mvc.el`). That will cause issues when a user uses `normal-top-level-add-subdirs-to-load-path`. It also confuses the tools I use to maintain the Emacsmirror.

Please rename that file to something like `widget-mvc-tests.el`. Or, but that's not as good, add the file `test/.nosearch`.

**Comment by kiwanami** [comment]
Hi @tarsius 
Thank you for your comment.
I renamed the test file. Is it OK?

**Comment by tarsius** [comment]
Yes. Thanks!
